chat/urls.py
from django.urls import path

from .views import InboxView, chat

urlpatterns = [
    path("chat/<int:receiver>", chat, name="chat"),
    path("inbox/<int:pk>", InboxView.as_view(), name="inbox"),
]


app_name = "chat"

findoffer/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("chat/", include("chat.urls", namespace="chat")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("django.contrib.auth.urls")),
    path("user/", include("accounts.urls", namespace="accounts")),
    path("social/", include("social_django.urls", namespace="social")),
    path("api/posts/", include("posts.api.urls", namespace="api")),
    path("api/users/", include("accounts.api.urls", namespace="api_users")),
    path(
        "api/password_reset/",
        include("django_rest_passwordreset.urls", namespace="password_reset"),
    ),
    path("docs/", include_docs_urls(title="FindOffer")),
    path(
        "schema",
        get_schema_view(
            title="FindOffer", description="API for the FindOffer site", version="1.0.0"
        ),
        name="FindOfferAPI-schema",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, LikeAPIView, CommentAPIView


app_name = "api"

router = DefaultRouter()
router.register("", PostViewSet, basename="post")


urlpatterns = router.urls
urlpatterns += [
    path("like/<int:pk>/", LikeAPIView.as_view(), name="like"),
    path("comment/<int:pk>/", CommentAPIView.as_view(), name="comment"),
]

posts/urls.py
from django.urls import path

# from posts.forms import OfferingCreationForm
from .views import (
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
    HomePageView,
    like_dislike,
    AddCommentView,
    PostCreateView,
)


urlpatterns = [
    path("<slug:slug>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("<slug:slug>/update/", PostUpdateView.as_view(), name="post_update"),
    path("post_create/", PostCreateView.as_view(), name="post_create"),
    path("<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
    path("", HomePageView.as_view(), name="home"),
    path("like/<int:post_id>/", like_dislike, name="like_dislike"),
    path("comment/<int:pk>/", AddCommentView.as_view(), name="add_comment"),
]

app_name = "posts"

posts/models.py
from random import random
import uuid
from django.db import models
from django.db.models.fields import BooleanField, related
from django.db.models.fields.related import ForeignKey
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from accounts.models import CustomUser


class SoftDeleteManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=650)
    author = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="author",
    )
    looking = models.BooleanField(default=False)
    offering = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.SmallIntegerField(default=0)
    users_liked = models.ManyToManyField(
        CustomUser, related_name="users_liked", blank=True
    )
    is_deleted = models.BooleanField(default=False)
    slug = models.SlugField(_("Slug"), max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            random_slug = uuid.uuid4()
            self.slug = slugify(random_slug)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url_offering(self):
        return reverse("posts:post_detail", args=[str(self.pk)])

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def restore(self):
        self.is_deleted = False
        self.save()

    def __str__(self):
        return f"{self.id}: {self.title}"

    all_objects = SoftDeleteManager()
    objects = models.Manager()


class LikeDislike(models.Model):
    user = ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = ForeignKey(Post, on_delete=models.CASCADE)
    value = models.SmallIntegerField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.value} - {self.post}"

    class Meta:
        unique_together = ("user", "post", "value")


class Comment(models.Model):
    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True, blank=True
    )
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.body[:40])

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment
from django import forms


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ("title", "body", "looking", "offering")

        error_messages = {
            "title": {"required": "Popunite ovo polje."},
            "body": {"required": "Popunite ovo polje."},
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)

        error_messages = {
            "body": {"required": "Popunite ovo polje."},
        }


class PostSearchForm(forms.Form):
    my_object = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
    )

posts/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import SAFE_METHODS, BasePermission, IsAuthenticated
from rest_framework import generics
from rest_framework.pagination import PageNumberPagination
from rest_framework import status
from rest_framework.response import Response
from yaml import serialize
from posts.models import Post, LikeDislike
from .serializers import CommentSerializer, LikeDislikeSerializer, PostSerializer


class CustomPermission(BasePermission):
    message = "Samo autor može da uređuje objavu."

    def has_object_permission(self, request, view, obj):
        if request.method in SAFE_METHODS:
            return True
        return obj.author == request.user


class PostPagination(PageNumberPagination):
    page_size = 4


class PostViewSet(viewsets.ModelViewSet):
    permission_classes = [CustomPermission]
    serializer_class = PostSerializer
    queryset = Post.objects.all()
    lookup_field = "pk"
    pagination_class = PostPagination

    def retrieve(self, request, pk):
        item = self.get_object()
        serializer = self.get_serializer(item)
        return Response(serializer.data)

    def list(self, request):
        serializer = self.get_serializer(self.get_queryset(), many=True)
        return self.get_paginated_response(self.paginate_queryset(serializer.data))

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        request = serializer.context["request"]
        serializer.is_valid(raise_exception=True)
        serializer.save(author=request.user)
        return Response(data=serializer.data, status=status.HTTP_201_CREATED)

    def put(self, request, pk):
        item = self.get_object()
        serializer = self.get_serializer(item)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(data=serializer.data, status=status.HTTP_202_ACCEPTED)

    def patch(self, request, pk):
        item = self.get_object()
        serializer = self.get_serializer(item)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(data=serializer.data, status=status.HTTP_202_ACCEPTED)

    def destroy(self, request, pk):
        item = self.get_object()
        item.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class LikeAPIView(generics.GenericAPIView):
    serializer_class = LikeDislikeSerializer
    permission_classes = [IsAuthenticated]

    def post(self, request, pk):
        serializer = self.get_serializer(data=request.data)
        request = serializer.context["request"]
        post = Post.objects.get(pk=pk)
        
        try:
            like = LikeDislike.objects.get(user=request.user, post=post)
            
            if like.value == 1:
                like.value -= 1
                post.likes -= 1
                post.users_liked.remove(request.user)
                like.save()
                post.save()
                return Response(status=status.HTTP_202_ACCEPTED, data={'value':like.value})

            elif like.value == 0:
                like.value += 1
                post.likes += 1
                post.users_liked.add(request.user)
                like.save()
                post.save()
                return Response(status=status.HTTP_202_ACCEPTED, data={'value':like.value})
        except:
            post.likes += 1
            post.users_liked.add(request.user)
            post.save()
            serializer.is_valid(raise_exception=True)
            serializer.save(user=request.user, post=post, value=1)
            return Response(status=status.HTTP_201_CREATED)

        return Response(status=status.HTTP_400_BAD_REQUEST)


class CommentAPIView(generics.GenericAPIView):
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticated]

    def post(self, request, pk):
        serializer = self.get_serializer(data=request.data)
        request = serializer.context["request"]
        post = Post.objects.get(pk=pk)
        serializer.is_valid(raise_exception=True)
        serializer.save(user=request.user, post=post)
        return Response(data=serializer.data, status=status.HTTP_201_CREATED)
        
        
        

posts/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    ListView,
)
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import LikeDislike, Post, Comment
from .forms import PostCreateForm, CommentForm


class HomePageView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 4
    template_name = "posts/home.html"

    def get_queryset(self):
        ordering = ["-updated", "-created"]
        searched = self.request.GET.get("searched", "")
        offering = self.request.GET.get("offering", "")
        looking = self.request.GET.get("looking", "")

        if searched and looking and offering:
            object_list = self.model.objects.filter(
                author__city__icontains=searched
            ).order_by(*ordering)
        elif searched and offering:
            object_list = self.model.objects.filter(
                offering=True, author__city__icontains=searched
            ).order_by(*ordering)
        elif searched and looking:
            object_list = self.model.objects.filter(
                looking=True, author__city__icontains=searched
            ).order_by(*ordering)
        else:
            object_list = self.model.objects.filter(
                author__city__icontains=searched
            ).order_by(*ordering)
        return object_list


class PostDetailView(DetailView):
    model = Post
    template_name = "posts/post_detail.html"


class PostUpdateView(SuccessMessageMixin, UpdateView):
    model = Post
    template_name = "posts/post_update.html"
    fields = ["title", "body"]
    success_url = reverse_lazy("posts:home")
    success_message = "Uspješno!"


class PostDeleteView(SuccessMessageMixin, DeleteView):
    model = Post
    template_name = "posts/post_delete.html"
    success_url = reverse_lazy("posts:home")
    success_message = "Obrisano!"


class PostCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    form_class = PostCreateForm
    template_name = "posts/post_new.html"
    success_url = reverse_lazy("posts:home")
    success_message = "Uspješno!"

    def form_valid(self, form):
        form.instance.author = self.request.user
        offering = self.request.GET.get("offering", "")
        looking = self.request.GET.get("looking", "")
        if looking:
            form.instance.looking = True
        elif offering:
            form.instance.offering = True
        return super().form_valid(form)


class AddCommentView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = "posts/add_comment.html"
    success_url = reverse_lazy("posts:home")
    success_message = "Uspješno!"

    def form_valid(self, form):
        form.instance.post_id = self.kwargs["pk"]
        form.instance.user = self.request.user
        return super().form_valid(form)


@login_required
def like_dislike(request, post_id):
    post = Post.objects.get(pk=post_id)
    try:
        like = LikeDislike.objects.get(user=request.user, post=post)
        if like.value == 1:
            like.value -= 1
            post.likes -= 1
            post.users_liked.remove(request.user)
            like.save()
            post.save()
            return redirect("posts:home")
        elif like.value == 0:
            like.value += 1
            post.likes += 1
            post.users_liked.add(request.user)
            like.save()
            post.save()
            return redirect("posts:home")
    except:
        new_like = LikeDislike(user=request.user, post=post, value=1)
        post.likes += 1
        post.users_liked.add(request.user)
        post.save()
        new_like.save()
        return redirect("posts:home")
    return HttpResponse("Greška! Molimo pokušajte ponovo.")

templates/posts/add_comment.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}

 <div id="app">
  <div class="section">
    <div class="container">
      <div class="title">Dodaj komentar</div>
      <div class="is-flex is-justify-content-left is-align-content-center ml-6">
        <div class="main-container">
          <form method="POST">
          {% csrf_token %}
          <label style="font-size: large;" class="has-text-weight-bold" 
            for="{{ form.body.id_for_label }}">Sadržaj</label>
              <div class="field m-3">
                <p class="control has-icons-left has-icons-right"></p>
                <textarea type='text' rows="4" cols="16" 
                style="min-width: 360px; text-align-last: initial;" 
                class="textarea is-medium" id="{{ form.body.id_for_label }}" 
                name="{{ form.body.html_name }}"
                  ></textarea>
                {{ form.body.errors }}
              </div>
            <button type="submit" class="button is-primary">Potvrdi</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/posts/home.html
{% extends 'base.html' %}


{% block title %}{% endblock %}



{% block content %}
   
  
  
<div class="is-flex-direction-column" 
style="display: grid; grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;">
    
{% for obj in object_list %}
<div class="card mt-6" style="grid-column: 3/8;">

    <div class="card-content ">
        <div class="media">
            <div class="media-left">
                <figure class="image is-48x48">
                    <img src='/media/profile_pics/{{obj.author.image}}' 
                    class="is-rounded">
                </figure>
            </div>
            <div class="media-content">
                <p class="title is-4" style="font-size: large; white-space:wrap; 
                                        overflow-wrap: break-word;">
                    <a onMouseOver="this.style.color='hsl(171, 100%, 41%)'" 
                    onMouseOut="this.style.color='#000000'"
                    id='title' style="text-decoration: none; color: black;"
                    href="#">{{ obj.title }}</a>
                </p>
                <p class="subtitle is-6" 
                style="overflow-wrap: break-word; white-space: wrap;">
                    {{obj.author.first_name}}&nbsp;{{obj.author.last_name}}: 
                                 &nbsp;{{obj.author.city}}
                </p>
                </div>
                <div class="media-right">
                    <a href="{% url 'chat:chat' obj.author.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" 
                        class="image is-32x32" fill="none" viewBox="0 0 24 24" 
                        stroke="currentColor"><path stroke-linecap="round" 
                        stroke-linejoin="round" stroke-width="2"  
                        d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 
                        002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z">
                        </svg>
                    </a>
                </div>
        </div>
        <hr>
        <div class="content">
            <p style="white-space:wrap; overflow-wrap: 
            break-word; color: black;">{{obj.body}}</p>
            <br>
            <div class="is-pulled-right	">
                {% if request.user == obj.author %}
                    <a href="{% url 'posts:post_update' obj.slug %}" 
                    class="button is-primary is-small">Promijeni</a>
                    <a href="{% url 'posts:post_delete' obj.slug %}" 
                    class="button is-primary is-small">Obriši</a>
                {% else %}
                    {% if user not in obj.users_liked.all %}
                        <div class='like-form is-inline-block'>
                        <a class="button is-primary is-small" 
                        href="{% url 'posts:like_dislike' post_id=obj.pk %}">Like</a>
                    </div>
                    {% else %}
                        <div class='like-form is-inline-block'>
                        <a class="button is-danger is-small"
                        href="{% url 'posts:like_dislike' post_id=obj.pk %}">Unlike</a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <br>
        <p>{{obj.created|date:"d-m-y" }}&nbsp;{{obj.created|time:"H:i"}}</p>
        <footer>
            <hr>
                <a class="button is-primary is-small" 
                href="{% url 'posts:add_comment' obj.id %}">Dodaj komentar</a>
            {% if obj.comments.all %}
            <hr>
            <p class="title is-4 mt-2 ml-2">Komentari</p>
            <hr>
            {% endif %}
            {% for comment in obj.comments.all %}
            <article class="content">
                <figure class="is-pulled-left image is-32x32">
                    <img src="/media/profile_pics/{{comment.user.image}}" 
                    class="is-rounded">
                </figure>
                <div class="media-content">
                    <p>{{obj.author.first_name}}&nbsp;{{obj.author.last_name}}
                        <br>
                        <span>{{ comment.body }}</span>
                    </p>
                </div>
            </article>
            <hr>
            {% endfor %}
        </footer>
    </div>
</div>
{% endfor %}
</div>
<br> <br>
{% if page_obj %}
<div class="pagination is-rounded" style="justify-content: center;">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1" class="pagination-link">
            <<</a>
                <a href="?page={{ page_obj.previous_page_number }}" 
                                class="pagination-previous">
                    <</a>
        {% endif %}

        <span class="pagination-ellipsis" style="font-weight: 500; color: black;">
            Stranica {{ page_obj.number }} od {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <a class="pagination-next" 
            href="?page={{ page_obj.next_page_number }}">></a>
        <a class="pagination-link" 
            href="?page={{ page_obj.paginator.num_pages }}">>></a>
        {% endif %}
    </span>
</div>
{% endif %}

{% endblock %}

templates/posts/post_delete.html
{% extends 'base.html' %}
{% block content %}
<div id="app">
  <div class="section">
    <div class="container">
      <div class="title">Da li ste sigurni da želite da obrišete objavu?</div>
      <form action="" method="POST">
        {% csrf_token %}
          
        <div class="field m-3 is-justify-content-center">
          <p class="control">
            <button type="submit" class="button is-success">
              Potvrdi
            </button>            
          </p>
        </div>
      </form>
   </div>
  </div>
</div>

{% endblock content %}

templates/posts/post_detail.html
<!-- WORK IN PROGRESS - NOT COMPLETED!!! -->

{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
{{post}}
<p>{{ post.body|linebreaks }}</p>
<hr>
<h2>Comments</h2>
<br>
<h1>Add comment</h1>
<a href="{% url 'posts:add_comment' post.id %}" 
class="button is-primary">Dodaj komentar</a>
 <br>
{% if not post.comments.all %}
    NO COMMENTS YET
{% else %}



{% for comment in post.comments.all %}
{{ comment.created|timesince }} ago
<br>
<p>{{ comment.body }}</p>
{% endfor %}
{% endif %}


{% endblock %}

templates/posts/post_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{% endblock %}

{% block content %}


    
  <div class="section">
<div class="title">Kreiraj objavu</div>
  </div>



<div class="is-flex is-justify-content-left is-align-content-center ml-6">
  <div class="main-container">
    
    <form method='post'>
        {% csrf_token %}
        <label class="has-text-weight-bold" 
        for="{{ form.title.id_for_label }}">Naslov</label>
        <div class="field m-3">
          <p class="control has-icons-left has-icons-right"></p>
          <input class="input" id="{{ form.title.id_for_label }}" 
          name="{{ form.title.html_name }}"
            type="{{form.title.widget_type}}" {% if form.title.value != None %} 
            value="{{form.title.value}}"{% endif %} />
          {{ form.title.errors }} 
          </div>
        <label class="has-text-weight-bold" 
          for="{{ form.body.id_for_label }}">Sadržaj</label>
        <div class="field m-3">
          <p class="control has-icons-left has-icons-right"></p>
          <textarea type='text' rows="4" cols="66" 
          style="min-width: 360px; text-align-last: initial;" 
          class="textarea is-medium" id="{{ form.body.id_for_label }}" 
          name="{{ form.body.html_name }}"
              ></textarea>
          {{ form.body.errors }}
          <div class="control m-1">
            <label class="checkbox">
            <input name='looking' type="checkbox">
              Tražim
            </label>
            <label class="checkbox">
            <input name='offering' type="checkbox">
              Nudim
            </label>
          </div>
        </div>
        <div class="field m-3 is-justify-content-center">
          <p class="control">
            <button type="submit" class="button is-success">
              Objavi
            </button>            
          </p>
        </div>
    </form>
  </div>
</div>





{% endblock %}

templates/posts/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{% endblock %}

{% block content %}


      
<div class="section">
  <div class="container">
    <div class="title">Promijeni objavu</div>
    </div>
  </div>
</div>


<div class="is-flex is-justify-content-left is-align-content-center ml-6">
  <div class="main-container">
    <form method='post'>
        {% csrf_token %}
        <label class="has-text-weight-bold" 
        for="{{ form.title.id_for_label }}">Naslov</label>
        <div class="field m-3">
          <p class="control has-icons-left has-icons-right"></p>
          <input class="input" id="{{ form.title.id_for_label }}" 
                        name="{{ form.title.html_name }}"
            type="{{form.title.widget_type}}" {% if form.title.value != None %} 
                                    value="{{form.title.value}}"{% endif %} />
          {{ form.title.errors }} 
        </div>
        <label class="has-text-weight-bold" 
        for="{{ form.body.id_for_label }}">Sadržaj</label>
        <div class="field m-3">
          <p class="control has-icons-left has-icons-right"></p>
          
          <textarea type='text' rows="4" cols="66" 
          style="text-align-last: initial; min-width: 360px;" class="textarea is-medium" 
          id="{{ form.body.id_for_label }}" name="{{ form.body.html_name }}"
            ></textarea>
          {{ form.body.errors }}
        </div>
        <div class="field m-3 is-justify-content-center">
          <p class="control">
            <button type="submit" class="button is-success">
              Objavi
            </button>            
          </p>
        </div>
    </form>
  </div>
</div>





{% endblock %}