accounts/api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)

from .views import (BlackListTokenView, ChangePasswordAPIView, SignUpAPIView,
                    UserUpdateAPIView)

app_name = "api_users"

urlpatterns = [
    path("login/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("login/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("register/", SignUpAPIView.as_view(), name="create_user"),
    path("logout/blacklist/", BlackListTokenView.as_view(), name="blacklist"),
    path(
        "change_password/<int:pk>/",
        ChangePasswordAPIView.as_view(),
        name="change_password",
    ),
    path(
        "update_profile/<int:pk>/", UserUpdateAPIView.as_view(), name="update_profile"
    ),
]

accounts/urls.py
from django.urls import path

from .views import ChangePassword, SignUpView, UserUpdateView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("my_profile/<slug:slug>", UserUpdateView.as_view(), name="my_profile"),
    path("change-password/", ChangePassword.as_view(), name="change_password"),
]

app_name = "users"

chat/urls.py
from django.urls import path

from .views import InboxView, chat

urlpatterns = [
    path("chat/<int:receiver>", chat, name="chat"),
    path("inbox/<int:pk>", InboxView.as_view(), name="inbox"),
]


app_name = "chat"

findoffer/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("chat/", include("chat.urls", namespace="chat")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("django.contrib.auth.urls")),
    path("user/", include("accounts.urls", namespace="accounts")),
    path("social/", include("social_django.urls", namespace="social")),
    path("api/posts/", include("posts.api.urls", namespace="api")),
    path("api/users/", include("accounts.api.urls", namespace="api_users")),
    path(
        "api/password_reset/",
        include("django_rest_passwordreset.urls", namespace="password_reset"),
    ),
    path("docs/", include_docs_urls(title="FindOffer")),
    path(
        "schema",
        get_schema_view(
            title="FindOffer", description="API for the FindOffer site", version="1.0.0"
        ),
        name="FindOfferAPI-schema",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import uuid
from django.core.validators import RegexValidator
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin, UserManager)
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

alphanumeric = RegexValidator(r"^[a-zA-Z]*$", "Dozvoljena su samo slova.")


class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, password2, is_staff, is_superuser, **kwargs):
        now = timezone.now()
        if not email:
            raise ValueError("Unesite email adresu.")
        if not password:
            raise ValueError("Unesite lozinku.")

        email = self.normalize_email(email).lower()
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **kwargs,
        )

        user.set_password(password)
        user.staff = is_staff
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, password2=None, **kwargs):
        return self._create_user(email, password, password2, False, False, **kwargs)

    def create_superuser(self, email, password=None, password2=None, **kwargs):
        return self._create_user(email, password, password2, True, True, **kwargs)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name="email",
        max_length=70,
        unique=True,
        error_messages={"unique": "Korisnik sa ovom email adresom već postoji."},
    )
    first_name = models.CharField(
        verbose_name="first_name", max_length=40, validators=[alphanumeric]
    )
    last_name = models.CharField(
        verbose_name="last_name", max_length=40, validators=[alphanumeric]
    )
    city = models.CharField(
        verbose_name="city", max_length=60, validators=[
            RegexValidator(
                regex='^[\w]+([-_\s]{1}[a-z]+)*$',
                message='Molimo Vas koristite samo slova.'
            )
        ]
    )
    date_joined = models.DateTimeField(verbose_name="joined", auto_now_add=True)
    last_seen = models.DateTimeField(verbose_name="last_seen", auto_now=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")
    slug = models.SlugField(_("Slug"), max_length=255, unique=True)

    # is_superuser = models.BooleanField(default=False)
    # user_permissions = models.PositiveIntegerField(default=None)

    def save(self, *args, **kwargs):
        if not self.slug:
            random_slug = uuid.uuid4()
            self.slug = slugify(random_slug)
        super(CustomUser, self).save(*args, **kwargs)

    objects = UserManager()
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name", "city"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

accounts/forms.py
import random

from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.forms.models import ModelForm
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kargs):
        super(CustomUserCreationForm, self).__init__(*args, **kargs)

    class Meta:
        model = CustomUser
        fields = ("first_name", "last_name", "email", "city")
        labels = {
            "first_name": "Ime",
            "last_name": "Prezime",
            "city": "Grad",
            #'country': 'Država',
        }
        error_messages = {
            "password_mismatch": {
                _("Lozinke se ne podudaraju"),
            },
        }


class CustomUserChangeForm(ModelForm):
    def __init__(self, *args, **kargs):
        super(CustomUserChangeForm, self).__init__(*args, **kargs)

    class Meta:
        model = CustomUser
        fields = (
            "first_name",
            "last_name",
            "email",
            "city",
        )
        labels = {
            "first_name": "Ime",
            "last_name": "Prezime",
            "city": "Grad",
        }

accounts/api/views.py
from rest_framework import generics, status
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.tokens import RefreshToken

from posts.api.views import CustomPermission
from accounts.models import CustomUser
from .serializers import (ChangePasswordSerializer,
                          RegisterCustomUserSerializer, UpdateUserSerializer)


class SignUpAPIView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        serializer = RegisterCustomUserSerializer(data=request.data)
        if serializer.is_valid():
            new_user = serializer.save()
            if new_user:
                return Response(data=serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserUpdateAPIView(generics.UpdateAPIView):
    queryset = CustomUser.objects.all()
    permission_classes = [
        CustomPermission,
    ]
    serializer_class = UpdateUserSerializer

    def patch(self, request, pk):
        user = self.get_object()
        serializer = self.get_serializer(user, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(data=serializer.data, status=status.HTTP_202_ACCEPTED)


class BlackListTokenView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        try:
            refresh_token = request.data["refresh"]
            token = RefreshToken(refresh_token)
            token.blacklist()
            return Response(status=status.HTTP_205_RESET_CONTENT)
        except Exception as e:
            return Response(status=status.HTTP_400_BAD_REQUEST)


class ChangePasswordAPIView(generics.UpdateAPIView):
    serializer_class = ChangePasswordSerializer
    permission_classes = (CustomPermission,)

    def update(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(status=status.HTTP_200_OK)

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import BadHeaderError, send_mail
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views.generic import CreateView, UpdateView

from chat.models import Message
from .models import CustomUser
from .forms import CustomUserChangeForm, CustomUserCreationForm



class SignUpView(SuccessMessageMixin, CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("posts:home")
    template_name = "registration/signup.html"
    success_message = "Uspješno ste kreirali profil!"

    def form_valid(self, form):
        validator = super().form_valid(form)
        user = authenticate(
            email=form.cleaned_data["email"], password=form.cleaned_data["password1"]
        )
        login(self.request, user)
        return validator


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = CustomUserChangeForm
    model = CustomUser
    success_url = reverse_lazy("posts:home")
    template_name = "accounts/profile.html"
    success_message = "Uspješno ste ažurirali profil!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get the number of unseen messages
        context["inbox_count"] = Message.objects.filter(
            ~Q(sender=self.request.user),
            Q(seen=False),
            (Q(chat__user1=self.request.user) | Q(chat__user2=self.request.user)),
        ).count()
        return context


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data["email"]
            associated_users = CustomUser.objects.filter(Q(email=data))
            if associated_users.exists():

                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "main/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        "domain": "127.0.0.1:8000",
                        "site_name": "Website",
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        "token": default_token_generator.make_token(user),
                        "protocol": "http",
                    }
                    email = render_to_string(email_template_name, c)
                    try:

                        send_mail(
                            subject,
                            email,
                            "admin@example.com",
                            [user.email],
                            fail_silently=False,
                        )
                    except BadHeaderError:

                        return HttpResponse("Invalid header found.")

                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(
        request=request,
        template_name="password_reset.html",
        context={"password_reset_form": password_reset_form},
    )


class ChangePassword(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy("posts:home")
    template_name = "accounts/password.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get the number of unseen messages
        context["inbox_count"] = Message.objects.filter(
            ~Q(sender=self.request.user),
            Q(seen=False),
            (Q(chat__user1=self.request.user) | Q(chat__user2=self.request.user)),
        ).count()
        return context

templates/accounts/password.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block content %}



<div class="section" style="display: grid; grid-template-columns: 1fr 1fr 1fr 1fr;">
    <div style="grid-column: 1;" 
        class="title">Promijeni lozinku
    </div>
    <div class="container" style="grid-column: 3;">
        <img src='/media/profile_pics/{{request.user.image}}' 
        class="image is-128x128" style="border-radius: 50%;">
    </div>
</div>

<div class="section">
    <div class="columns" style="display: grid; 
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr;">
        <div style="grid-column: 1;">
        <aside class="menu">
            <p class="menu-label ml-3">
            Menu
            </p>
            <ul class="menu-list">
            <li><a href="{% url 'accounts:my_profile' request.user.slug %}"
                >Osnovni podaci</a></li>
            <li><a>Sigurnost</a></li>
            <li>
                <a href="{% url 'chat:inbox' request.user.id %}">
                    Inbox ({{ inbox_count }})</a>
            </li>
            </ul>  
        </aside>
        </div>
        <div style="grid-column: 3/5;">
            <form id="control" method="post">
                {% csrf_token %}
                <div class="field">
                {% for field in form %}
                {{ field.label_tag }}
                    <div class="field m-3">
                    <p class="control has-icons-left has-icons-right"></p>
                    <input class="input" id="{{ field.id_for_label }}" 
                    name="{{ field.html_name }}"
                        type="{{field.widget_type}}" 
                        {% if field.value != None and field.value != 'default.jpg' %}
                        value="{{field.value}}"{% endif %}/>
                    {{ field.errors }}
                    </div>
                {% endfor %}
                <br>
                <div class="field m-3">
                    <button class="button is-primary is-medium" 
                    type="submit">Promijeni lozinku</button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}
{% block content %}

<div class="section" style="display: grid; grid-template-columns: 1fr 1fr 1fr 1fr;">
    <div style="grid-column: 1;" 
    class="title">Uredi profil
    </div>
    <div class="container" style="grid-column: 3;">
            <img src='/media/profile_pics/{{request.user.image}}' 
            class="image is-128x128" style="border-radius: 50%;">
    </div>
</div>

<div class="section">
    <div class="columns" style="display: grid; 
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr;">
        <div style="grid-column: 1;">
            <aside class="menu">
                <p class="menu-label ml-3">
                Menu
                </p>
                <ul class="menu-list">
                <li>
                    <a href="{% url 'accounts:my_profile' request.user.slug %}">
                        Osnovni podaci</a>
                </li>
                <li><a href="{% url 'accounts:change_password' %}">Sigurnost</a></li>
                <li>
                    <a href="{% url 'chat:inbox' request.user.id %}">Inbox 
                    {% if inbox.count >= 1 %}({{ inbox_count }}){% endif %}</a>
                </li>
                </ul>      
            </aside>
        </div>
        <div style="grid-column: 3/5;">
            <form id="control" method="post">
                {% csrf_token %}
                <div class="field">
                {% for field in form %}
                {{ field.label_tag }}

                <div class="field m-3">
                <p class="control has-icons-left has-icons-right"></p>
                <input class="input" id="{{ field.id_for_label }}" 
                name="{{ field.html_name }}"
                    type="{{field.widget_type}}" 
                    {% if field.value != None and field.value != 'default.jpg' %}
                    value="{{field.value}}"{% endif %}/>
                {{ field.errors }}
                </div>
                {% endfor %}
                <br>
                <div class="field m-3">
                    <button class="button is-primary is-medium" 
                    type="submit">Potvrdi izmjene</button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}