accounts/urls.py
from django.urls import path

from .views import ChangePassword, SignUpView, UserUpdateView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("my_profile/<slug:slug>", UserUpdateView.as_view(), name="my_profile"),
    path("change-password/", ChangePassword.as_view(), name="change_password"),
]

app_name = "users"

chat/urls.py
from django.urls import path

from .views import InboxView, chat

urlpatterns = [
    path("chat/<int:receiver>", chat, name="chat"),
    path("inbox/<int:pk>", InboxView.as_view(), name="inbox"),
]


app_name = "chat"

findoffer/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("chat/", include("chat.urls", namespace="chat")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("django.contrib.auth.urls")),
    path("user/", include("accounts.urls", namespace="accounts")),
    path("social/", include("social_django.urls", namespace="social")),
    path("api/posts/", include("posts.api.urls", namespace="api")),
    path("api/users/", include("accounts.api.urls", namespace="api_users")),
    path(
        "api/password_reset/",
        include("django_rest_passwordreset.urls", namespace="password_reset"),
    ),
    path("docs/", include_docs_urls(title="FindOffer")),
    path(
        "schema",
        get_schema_view(
            title="FindOffer", description="API for the FindOffer site", version="1.0.0"
        ),
        name="FindOfferAPI-schema",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

# from posts.forms import OfferingCreationForm
from .views import (
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
    HomePageView,
    like_dislike,
    AddCommentView,
    PostCreateView,
)


urlpatterns = [
    path("<slug:slug>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("<slug:slug>/update/", PostUpdateView.as_view(), name="post_update"),
    path("post_create/", PostCreateView.as_view(), name="post_create"),
    path("<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
    path("", HomePageView.as_view(), name="home"),
    path("like/<int:post_id>/", like_dislike, name="like_dislike"),
    path("comment/<int:pk>/", AddCommentView.as_view(), name="add_comment"),
]

app_name = "posts"

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block title %}<title></title>{% endblock %}
  <link rel="stylesheet" href="{% static 'bulma/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'main.css' %}">


  {% if user.is_authenticated %}
  <nav class="navbar is-dark" style="border-radius: 0 !important; 
                  -moz-border-radius: 0 !important;">

    <div class="navbar-brand" style="margin-top: 2px;">
      <a href="{% url 'posts:home' %}">
        <figure class="image is-96x96">
          <img src='/media/logo.png' class="is-rounded">
        </figure>
      </a>
      <div class="navbar-item center">
        <form method="GET">
          <div class="control m-1 is-inline-block">
            <input name='searched' class="input" size="30" type="text" 
                          placeholder="Ime grada/opštine">
          </div>
          <div class="control m-1">
            <label class="checkbox">
              <input name='looking' type="checkbox">
              Tražim
            </label>
            <label class="checkbox">
              <input name='offering' type="checkbox">
              Nudim
            </label>
            <input type="submit" class="button is-info m-0 is-small" 
            value="Pretraga" style="width: 50%;">
          </div>
        </form>
      </div>

      <span class="navbar-burger burger" data-target='navbarMenu'>
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>

    <div id='navbarMenu' class="navbar-menu" 
      style="background-color: hsl(0, 0%, 21%);">
      
      <div class="navbar-end" style="margin-right: 5px; ">
          <div class="navbar-item">
        <div class="buttons">
        <a href="{% url 'posts:post_create' %}" 
        class="button is-primary is-outlined">Tražim/Nudim</a>
        <a href="{% url 'accounts:my_profile' request.user.slug %}" 
        class="button is-primary is-outlined">Profil</a>
        <a href="{% url 'logout' %}"
          class="button is-danger is-outlined">Odjavi se</a>
        </div>
          </div>
      </div>
  </nav>

  {% else %}
  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-light" href="{% url 'users:signup' %}">
            <strong>Registracija</strong>
          </a>
          <a class="button is-primary" href="{% url 'login' %}">
            Prijavi se
          </a>
        </div>
      </div>
    </div>
  </nav>
  {% endif %}
  {% include 'messages.html' %}
</head>
<body>

  {% block content %}
  {% endblock %}

  <script type="text/javascript">
    // burger menu
    (function () {
      var burger = document.querySelector('.burger');
      var navbarMenu = document.querySelector('#' + burger.dataset.target);

      burger.addEventListener('click', function () {
        burger.classList.toggle('is-active');
        navbarMenu.classList.toggle('is-active');
      });
    })();
    // dropdown is-active on click
    var dropdown = document.querySelector('.dropdown');
    dropdown.addEventListener('click', function (event) {
      event.stopPropagation();
      dropdown.classList.toggle('is-active');
    });
  </script>
</body>

</html>

templates/messages.html
{% for message in messages %}
<div class="alert {{ message.tags }} notification" role="alert">
    <button type="button" class="delete" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p style="color: black;">{{ message }} </p>
</div>
{% endfor %}    

templates/profile.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block content %}



<div class="section" style="display: grid; grid-template-columns: 1fr 1fr 1fr 1fr;">
    <div style="grid-column: 1;" 
    class="title">Uredi profil
    </div>
    <div class="container" style="grid-column: 3;">
            <img src='/media/profile_pics/{{request.user.image}}' 
            class="image is-128x128" style="border-radius: 50%;">
    </div>
</div>

<div class="section">
    <div class="columns" style="display: grid; 
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr;">


        <div  style="grid-column: 1;">
        <aside class="menu">
            <p class="menu-label">
            General
            </p>
            <ul class="menu-list">
            <li><a>Dashboard</a></li>
            <li><a>Customers</a></li>
            </ul>
            <p class="menu-label">
            Administration
            </p>
            <ul class="menu-list">
            <li><a>Team Settings</a></li>
            <li>
                <a class="is-active">Manage Your Team</a>
                <ul>
                <li><a>Members</a></li>
                <li><a>Plugins</a></li>
                <li><a>Add a member</a></li>
                </ul>
            </li>
            <li><a>Invitations</a></li>
            <li><a>Cloud Storage Environment Settings</a></li>
            <li><a>Authentication</a></li>
            </ul>
            <p class="menu-label">
            Transactions
            </p>
            <ul class="menu-list">
            <li><a>Payments</a></li>
            <li><a>Transfers</a></li>
            <li><a>Balance</a></li>
            </ul>
        </aside>
        </div>


        <div style="grid-column: 3/5;">
            <form id="control" method="post">
                {% csrf_token %}
                <div class="field">
                {% for field in form %}
                {{ field.label_tag }}

                    <div class="field m-3">
                    <p class="control has-icons-left has-icons-right"></p>
                    <input class="input" id="{{ field.id_for_label }}" 
                    name="{{ field.html_name }}"
                        type="{{field.widget_type}}" 
                        {% if field.value != None and field.value != 'default.jpg' %}
                        value="{{field.value}}"{% endif %}/>
                    {{ field.errors }}
                    </div>
                {% endfor %}
                <br>
                <div class="field m-3">
                    <button class="button is-primary is-medium" 
                    type="submit">Potvrdi</button>
                    </div>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}